# Generated by Django 5.1.4 on 2025-06-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
