# Generated by Django 5.1.4 on 2025-06-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_alter_participant_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='token_number',
            field=models.IntegerField(default=0),
        ),
    ]
