# Generated by Django 5.1.4 on 2025-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_alter_participant_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
