# Generated by Django 5.1.4 on 2025-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_participant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='home_parish',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
